### PR TITLE
Fix empty result if process is altered

### PR DESCRIPTION
**Pull request by publicqi**
Use pid check to see if the page table information needs to be initiated. Resolve the problem that for a same gdb session, pt-dump only dumps the first process gdb attaches to.

### CODE REVIEW

**Comment by martinradev** [comment]
Thanks for the pull request.
So the problem occurs when you re-attach to another target while in the same session? Makes sense.
I can check the patch later this week and merge it.

**Comment by disconnect3d** [comment]
@martinradev ping :P

**Comment by martinradev** [comment]
Will get to it this weekend I think.

I've been working on some bigger perf and correctness improvements for the project.

**Comment by martinradev** [comment]
Updated @publicqi 's change and pushed it. Original author is preserved.

Thank you for your contribution. Closing the pull request.

**Pull request closed without merging**
