### PR TITLE
properly handle python path injection

### PR DESCRIPTION
**Pull request by Kyle-Kyle**

### CODE REVIEW

**Comment by Kyle-Kyle** [comment]
the original implementation fails when there is `~` in the path

**Comment by martinradev** [comment]
What about `source /home/kyle/scripts/gdb-pt-dump/pt.py`?

**Comment by Kyle-Kyle** [comment]
I haven't tried it yet. But I think it will work.

**Comment by martinradev** [comment]
Yeah, that's what I do locally. I think using ~ and adding your patch wouldn't be a good solution since the script may not be placed in the user's path. e.g. if it's run under root let's say.

**Comment by martinradev** [comment]
Thanks for your PR though. Will not merge and closing.

**Pull request closed without merging**
